name: Net CLI
on: [push]

jobs:
    build:
        runs-on: [self-hosted, Windows, X64]
        steps:
          - uses: actions/checkout@v7
          
          - name: Display Local .NET info
            run : |
              dotnet --info
              dotnet workload list

          - name: Display version
            run: dotnet --version

          - name: Build Project
            run: dotnet build MauiApp1/MauiApp1.csproj -f net10.0-windows10.0.19041.0 -c Release

          - name: Test Project
            run: dotnet test TestProject1/TestProject1.csproj