name: Net CLI
on: [push]

jobs:
    build:
        runs-on: windows-latest
        
    steps:
        - uses: actions/checkout@v7

        - name: Setup dotnet
          uses: actions/setup-dotnet@v4